path: ../../../../data/roadline20251023
train: train
val: val

names:
  0: white solid lane line
  1: yellow solid lane line
  2: white dashed lane line
  3: yellow dashed lane line
  4: zebra crossing
  5: lane barrier
  6: road teeth marking
